### ISSUE TITLE
"Not set up: Credentials missing"

### ISSUE THREAD

**Issue by nyok92** [SuperFlyTV/spreadsheet-gateway#21]
Hi !
When i put the credentials.json in spreadsheet gateway, it doesn't do anything. 
The gateway status is stuck on "Not set up: Credentials missing"
Thanks for any help

**Comment by brandonkal** [comment]
@nyok92 Did you figure this out? Where did you put the credentials.json as I don't see any mention of that in the docs.

**Comment by brandonkal** [comment]
Based on reading the code I added this volume to mount the credentials.json file:
```
./spreadsheet-gateway/credentials.json:/opt/sofie-spreadsheet-gateway/credentials.json
```

Still it doesn't work.

Docker restarted the gateway on startup first for not connecting and then for this:
```
BulkWriteError: E11000 duplicate key error collection: meteor.peripheralDevices index: _id_ dup key
```

I'm also seeing this in core which could be a contributing factor:

Sofie Automation version: 1.17.0

System Status: FAIL / BAD

Status Messages:
check systemTime: Error message: Error: Too few NTP-responses
check blueprintCompability_6mFBSPtWFeGos4Rhz: Integration version: Version mismatch: blueprint.integrationVersion version: "1.10.0" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)

check blueprintCompability_4KKuSAuMrfNMdEnM2: Integration version: Version mismatch: blueprint.integrationVersion version: "1.10.0" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)

check blueprintCompability_5bnDjzxy68quKdWam: Integration version: Version mismatch: blueprint.integrationVersion version: "1.10.0" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)

Spreadsheet Gateway: Not set up: Credentials missing
Spreadsheet Gateway: Not set up: Credentials missing

It seems to thing there are two spreadsheet gateways but there is only one running.

**Comment by baltedewit** [comment]
Hi @brandonkal,

The credentials are not stored on disk but rather in the database. They have to be uploaded through the settings UI. Unfortunately as of now we're a bit behind on maintenance and server-core contains a bug. The [API method](https://github.com/nrkno/tv-automation-server-core/blob/e870d883662c7297e45a2e00194b3c1bac45cf6e/meteor/server/api/peripheralDevice.ts#L620) expects a token but the [UI code](https://github.com/nrkno/tv-automation-server-core/blob/c86bd912cc747e6b6a7c278c5bd6af51f6430eb3/meteor/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx#L42) does not send it. I believe the token is meant to be used if we ever end up creating a cloud based platform for Sofie but as of now it's not needed.

If you are able to edit the code yourself it should be easy to just edit out the token and otherwise we do intend on fixing this _eventually_.

**Comment by brandonkal** [comment]
Hi @baltedewit,

Thanks for the pointer on the core issue.

I wasn't seeing an upload option in the spreadsheet gateway. I thought it was taking it from disk based on this line:

https://github.com/SuperFlyTV/spreadsheet-gateway/blob/5532faf5dd5ae75160cc8f9f115c1e183d15f064/index.js#L14

That file doesn't exist in the Docker image, but I'm guessing that's dead code even though it's been there for 2 years?

I will try to see if I can get this working without the token.

**Comment by baltedewit** [comment]
>That file doesn't exist in the Docker image, but I'm guessing that's dead code even though it's been there for 2 years?

I've not had much to do with this gateway myself, but judging from the git history I would say that file is just an old experiment. I do know that all the source code for the actual gateway should be in the src folder.

**Comment by rakibhossensweet** [comment]
here are no rundowns ingested into Sofie.

Sofie Automation version: 1.17.0


I saw some problem when I installing the sofie core can any one help me 

System Status: FAIL / BAD
Status Messages:
check blueprintCompability_c6eLKDwzEY2ZfzBTm: Integration version: Version mismatch: blueprint.integrationVersion version: "0.24.1" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)
check blueprintCompability_AYNfH8C7Yq4dRDjma: Integration version: Version mismatch: blueprint.integrationVersion version: "0.24.1" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)
check blueprintCompability_rdd2MAHCLJkNnpB5L: Integration version: Version mismatch: blueprint.integrationVersion version: "0.24.1" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.17.0 <1.18.0-0" (Blueprint has to be updated)
Spreadsheet Gateway: Not set up: Credentials missing

**Comment by brandonkal** [comment]
Using release 30 the credential uploads properly. The issue remains that the sample blueprints are not updated so I can't be sure if rundown import works.

**Comment by baltedewit** [comment]
@brandonkal there is a branch with blueprints that are aimed at release 33 (which works OK with release 30 of the gateway): https://github.com/SuperFlyTV/sofie-blueprints-spreadsheet/tree/feat/complete-rewrite

**Comment by nyok92** [comment]
@baltedewit hello, thanks for the tips and updates. I tried to make the blueprints, fist with dockerfile, then manually with yarn and yarn dist cmds. But each time i've got erors with the "prettier" module : 
Do i missed something ?
It has been a long time since i would like to test Sofie Tv automation,  but i don't have any MOS compatible software so the only chance is to try it with this spreadsheet system.
By the way thank you !

#14 62.40 /blueprints/src/showstyle0/helpers/graphics.ts
#14 62.40     2:10  error  Delete `StudioConfig·}·from·'../../studio0/helpers/config'⏎import·{·`                                                                                                                                           prettier/prettier
#14 62.40     5:10  error  Insert `StudioConfig·}·from·'../../studio0/helpers/config'⏎import·{·`                                                                                                                                           prettier/prettier
#14 62.40    60:43  error  Replace `·?·createAtemInputTimelineObjects(fullscreenAtemInput?.input·||·0,·config.casparcgLatency)·` with `⏎↹↹↹?·createAtemInputTimelineObjects(fullscreenAtemInput?.input·||·0,·config.casparcgLatency)⏎↹↹↹`  prettier/prettier
#14 62.40    68:65  error  Replace `.filter(v·=>·(v·!==·'true'·&&·v·!==·'false'))` with `⏎↹↹↹.filter((v)·=>·v·!==·'true'·&&·v·!==·'false')⏎↹↹↹`                                                                                            prettier/prettier
#14 62.40    85:6   error  Insert `,`                                                                                                                                                                                                      prettier/prettier
#14 62.40    87:43  error  Insert `,`                                                                                                                                                                                                      prettier/prettier
#14 62.40    98:65  error  Replace `.filter(v·=>·(v·!==·'true'·&&·v·!==·'false'))` with `⏎↹↹↹.filter((v)·=>·v·!==·'true'·&&·v·!==·'false')⏎↹↹↹`                                                                                            prettier/prettier
#14 62.40   115:6   error  Insert `,`                                                                                                                                                                                                      prettier/prettier
#14 62.40   116:5   error  Insert `,`                                                                                                                                                                                                      prettier/prettier
#14 62.40 
#14 62.40 /blueprints/src/showstyle0/part-adapters/titles.ts
#14 62.40   80:23  error  Insert `,`  prettier/prettier
#14 62.40   81:9   error  Insert `,`  prettier/prettier
#14 62.40   82:8   error  Insert `,`  prettier/prettier
#14 62.40 
#14 62.40 /blueprints/src/showstyle0/rundown/baseline.ts
#14 62.40    9:43  error  Replace `source` with `(source)`  prettier/prettier
#14 62.40   61:24  error  Insert `,`                        prettier/prettier
#14 62.40   63:6   error  Insert `,`                        prettier/prettier
#14 62.40   94:23  error  Insert `,`                        prettier/prettier
#14 62.40 
#14 62.40 /blueprints/src/showstyle0/spreadsheet-parsers/gfx.ts
#14 62.40   23:22  error  Insert `,`  prettier/prettier
#14 62.40 
#14 62.40 /blueprints/src/studio0/config-manifests.ts
#14 62.40   68:17  error  Insert `,`  prettier/prettier
#14 62.40   76:18  error  Insert `,`  prettier/prettier
#14 62.40 
#14 62.40 ✖ 19 problems (19 errors, 0 warnings)

**Comment by brandonkal** [comment]
@nyok92 I went ahead and formatted the files to make the build complete:
```
yarn run eslint . --ext .ts --ext .js --ignore-pattern dist --fix
```

@baltedewit Thank you for pointing out that rewrite branch, that saved me a lot of hassle.

I went ahead and built the suggested branch and uploaded those blueprints. With release30 (see docker-compose below) I still get version errors inside Sofie:


Sofie Automation version: 1.18.1

System Status: FAIL / BAD
Status Messages:
check blueprintCompability_AcNMdzEuayP2JYwFZ: Integration version: Version mismatch: blueprint.integrationVersion version: "1.20.0-nightly-release32-20210319-162613-563bf38.0" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.18.1 <1.19.0-0" (Blueprint has to be updated)
check blueprintCompability_sHucnAGCjzq5ZTi6N: Integration version: Version mismatch: blueprint.integrationVersion version: "1.20.0-nightly-release32-20210319-162613-563bf38.0" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.18.1 <1.19.0-0" (Blueprint has to be updated)
check blueprintCompability_QH6M8NM4efsNP59uX: Integration version: Version mismatch: blueprint.integrationVersion version: "1.20.0-nightly-release32-20210319-162613-563bf38.0" does not satisfy expected version range of core.@sofie-automation/blueprints-integration: ">=1.18.1 <1.19.0-0" (Blueprint has to be updated)
check blueprintConfig_sHucnAGCjzq5ZTi6N_studio_studio0: Config is missing required fields: Atem Sources, Atem Outputs
Spreadsheet Gateway: Watching folder '/Sofie'

docker-compose.yaml
```yaml
# This is NOT recommended to be used for a production deployment. It aims to quickly get an evaluation version of sofie running and serve as a basis for how to setup a production deployment
version: '3.3'
services:
  db:
    hostname: mongo
    image: mongo:4.2.8
    restart: always

    ports:
      - '3001:27017' # Expose mongo on the same port as dev meteor does
    volumes:
      - db-data:/data/db
    networks:
      - sofie

  core:
    hostname: core
    image: sofietv/tv-automation-server-core:release30
    restart: always
    ports:
      - '3000:3000' # Same port as meteor uses by default
    environment:
      PORT: '3000'
      MONGO_URL: 'mongodb://db:27017/meteor'
      ROOT_URL: 'http://localhost:3000'
    networks:
      - sofie
    volumes:
      - ./coredisk/:/opt/coredisk
      - snapshots:/mnt/snapshots
    depends_on:
      - db

  # playout-gateway:
  #   image: sofietv/tv-automation-playout-gateway:v1.0.0
  #   restart: always
  #   command: yarn start -host core -port 3000
  #   networks:
  #     - sofie
  #   depends_on:
  #     - core

  # Choose one of the following images, depending on which type of ingest gateway is wanted:

  spreadsheet-gateway:
    image: superflytv/sofie-spreadsheet-gateway:v0.1.3
    restart: always
    command: yarn start -host core -port 3000
    networks:
      - sofie
    depends_on:
      - core

networks:
  sofie:

volumes:
  db-data:
  snapshots:
```
